name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and test
      run: xcodebuild clean build test -project R&M.xcodeproj -scheme R&M -destination "name=iPhone 8,OS=13.4.1" OBJROOT=$(PWD)/build SYMROOT=$(PWD)/build | xcpretty -s